.github/workflows/upload_component.yml
iperf/CMakeLists.txt
iperf/LICENSE
iperf/README.md
iperf/idf_component.yml
iperf/include/iperf.h
iperf/iperf.c
pcap/CMakeLists.txt
pcap/LICENSE
pcap/idf_component.yml
pcap/include/pcap.h
pcap/src/pcap.c
pid_ctrl/CMakeLists.txt
pid_ctrl/LICENSE
pid_ctrl/idf_component.yml
pid_ctrl/include/pid_ctrl.h
pid_ctrl/src/pid_ctrl.c
qrcode/CMakeLists.txt
qrcode/LICENSE
qrcode/README.md
qrcode/esp_qrcode_main.c
qrcode/esp_qrcode_wrapper.c
qrcode/idf_component.yml
qrcode/include/qrcode.h
qrcode/qrcodegen.c
qrcode/qrcodegen.h

Add iperf, pcap, pid_ctrl, qrcode components

Add common example components

---

.github/workflows/build_example.yml
.github/workflows/build_test.yml
components/bh1750/bh1750.c
components/bh1750/idf_component.yml
components/bh1750/test/bh1750_test.c
components/es8311/es8311.c
components/es8311/idf_component.yml
components/fbm320/fbm320.c
components/fbm320/idf_component.yml
components/fbm320/test/fbm320_test.c
components/hts221/hts221.c
components/hts221/idf_component.yml
components/hts221/test/hts221_test.c
components/mag3110/idf_component.yml
components/mag3110/mag3110.c
components/mag3110/test/mag3110_test.c
components/mpu6050/idf_component.yml
components/mpu6050/mpu6050.c
components/mpu6050/test/mpu6050_test.c
components/ssd1306/idf_component.yml
components/ssd1306/ssd1306.c
components/ssd1306/test/ssd1306_test.c
esp32_azure_iot_kit/examples/sensors_example/main/sensors_example.c
esp32_azure_iot_kit/idf_component.yml
esp32_s2_kaluga_kit/esp32_s2_kaluga_kit.c
esp32_s2_kaluga_kit/examples/display_audio/main/bsp_kaluga_disp_audio_example.c
esp32_s2_kaluga_kit/idf_component.yml
esp32_s2_kaluga_kit/include/esp32_s2_kaluga_kit.h

Partly solves #10 
Closes #11 
Github actions are extended to be run on multiple targets and idf versions, including idf-master.

Forward compatibility with IDFv5.0

---

.github/workflows/upload_component.yml
components/lcd_touch/esp_lcd_touch_stmpe610/CMakeLists.txt
components/lcd_touch/esp_lcd_touch_stmpe610/README.md
components/lcd_touch/esp_lcd_touch_stmpe610/esp_lcd_touch_stmpe610.c
components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
components/lcd_touch/esp_lcd_touch_stmpe610/include/esp_lcd_touch_stmpe610.h
components/lcd_touch/esp_lcd_touch_stmpe610/license.txt

esp_lcd_touch: Add STMPE610 touch controller.

---

components/mpu6050/idf_component.yml
components/mpu6050/include/mpu6050.h
components/mpu6050/mpu6050.c
components/mpu6050/test/mpu6050_test.c

Include temp read from MPU6050 sensor.

Include celsius temp read (BSP-177)

---

.github/workflows/build_test.yml
components/bh1750/idf_component.yml
components/bh1750/test/bh1750_test.c
components/fbm320/idf_component.yml
components/fbm320/test/fbm320_test.c
components/hts221/idf_component.yml
components/hts221/test/hts221_test.c
components/mag3110/idf_component.yml
components/mag3110/test/mag3110_test.c
components/mpu6050/idf_component.yml
components/mpu6050/test/mpu6050_test.c
esp32_s2_kaluga_kit/idf_component.yml
examples/display_audio/main/bsp_kaluga_disp_audio_example.c
examples/display_audio/main/idf_component.yml
test_app/CMakeLists.txt

* Use new led_strip driver in kaluga BSP
* Build test_app with pedantic compiler flags

kaluga: Use new led_strip driver

---

components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
components/lcd_touch/esp_lcd_touch_tt21100/esp_lcd_touch_tt21100.c
components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml

Added some initial read into touch controllers for check, if I2C is working.

Add initial read into touch controllers, where is missing it.

---

components/lcd_touch/esp_lcd_touch/esp_lcd_touch.c
components/lcd_touch/esp_lcd_touch/idf_component.yml

lcd_touch: Fixed get functions.

---

.github/workflows/upload_component.yml
components/io_expander/esp_io_expander/CMakeLists.txt
components/io_expander/esp_io_expander/README.md
components/io_expander/esp_io_expander/esp_io_expander.c
components/io_expander/esp_io_expander/idf_component.yml
components/io_expander/esp_io_expander/include/esp_io_expander.h
components/io_expander/esp_io_expander/license.txt

This is a new main component to driver io expander chip. I also created two devices based on it.

Add new main component - esp_io_expander

---

components/lcd/esp_lcd_ra8875/README.md

On the basis of the issue #73, I added some hardware notes to the ra8875 LCD controller.

lcd: Updated hardware notes for ra8875 LCD controller.

---

.github/workflows/upload_component.yml
components/es7210/CMakeLists.txt
components/es7210/README.md
components/es7210/es7210.c
components/es7210/idf_component.yml
components/es7210/include/es7210.h
components/es7210/license.txt
components/es7210/priv_include/es7210_reg.h
components/es7210/test/CMakeLists.txt
components/es7210/test/es7210_test.c
test_app/CMakeLists.txt

Add a new  component `es7210`: a 4-channel audio ADC

add es7210 component (BSP-215)

---

components/io_expander/esp_io_expander/CMakeLists.txt
components/io_expander/esp_io_expander/esp_io_expander.c
components/io_expander/esp_io_expander/idf_component.yml
components/io_expander/esp_io_expander/include/esp_io_expander.h
test_app/CMakeLists.txt

The last version of esp_io_expander is not perfect. Fixed some errors according to comments in  #82 .

fix some error in esp_io_expander

---

SquareLine/boards/custom_waveshare_7inch/manifest.json
SquareLine/boards/esp32_s2_kaluga_kit/manifest.json
SquareLine/boards/esp32_s3_eye/manifest.json
SquareLine/boards/esp32_s3_usb_otg/manifest.json
SquareLine/boards/espbox/manifest.json
SquareLine/boards/espwroverkit/manifest.json
SquareLine/gen.py

Updated SquareLine generator for structure changes (GitHub issue Closes #80).

SquareLine: Update LVGL version and board names.

---

components/es7210/idf_component.yml
components/es7210/include/es7210.h

Added I2C addresses into header file.

es7210: Add I2C address to header.

---

components/bh1750/README.md
components/es7210/README.md
components/es8311/README.md
components/esp_lvgl_port/README.md
components/fbm320/README.md
components/hts221/README.md
components/io_expander/esp_io_expander/README.md
components/io_expander/esp_io_expander_tca9554/README.md
components/lcd/esp_lcd_gc9a01/README.md
components/lcd/esp_lcd_ili9341/README.md
components/lcd/esp_lcd_ra8875/README.md
components/lcd/esp_lcd_sh1107/README.md
components/lcd_touch/esp_lcd_touch/README.md
components/lcd_touch/esp_lcd_touch_ft5x06/README.md
components/lcd_touch/esp_lcd_touch_gt1151/README.md
components/lcd_touch/esp_lcd_touch_gt911/README.md
components/lcd_touch/esp_lcd_touch_stmpe610/README.md
components/lcd_touch/esp_lcd_touch_tt21100/README.md
components/mag3110/README.md
components/mpu6050/README.md
components/ssd1306/README.md
esp-box/README.md
esp32_azure_iot_kit/README.md
esp32_s2_kaluga_kit/README.md
esp32_s3_eye/README.md
esp32_s3_lcd_ev_board/README.md
esp32_s3_usb_otg/README.md
esp_wrover_kit/README.md

Added badges with versions in README files to following components:
- esp-box
- esp-32_azure_iot_kit
- esp32_azure_iot_kit
- esp32_s3_eye
- esp32_s3_lcd_ev_board
- esp32_s3_usb_otg
- esp_wrover_kit
Added badge with latest version in README files to remaining components in [components](https://github.com/espressif/esp-bsp/tree/master/components) subfolder and it's subfolders

Added badges with versions to READMEs of components

---

esp32_s3_lcd_ev_board/README.md
esp32_s3_lcd_ev_board/esp32_s3_lcd_ev_board.c
esp32_s3_lcd_ev_board/idf_component.yml
esp32_s3_lcd_ev_board/priv_include/bsp_sub_board.h
examples/display_lvgl_demos/partitions.csv

* fix some unsuitable headers in bsp
* remove partition table in example "display_lvgl_demos" which is unnecessary
* update some links in README

s3-lcd-ev-board: fix headers and remove partition table

---

SquareLine/common/LICENSE
SquareLine/gen.py

Add license file into each board package for SquareLine.

SquareLine: Added license file.

---

esp-box/esp-box.c
esp-box/idf_component.yml
esp-box/include/bsp/display.h
esp-box/include/bsp/touch.h
esp32_s2_kaluga_kit/esp32_s2_kaluga_kit.c
esp32_s2_kaluga_kit/idf_component.yml
esp32_s2_kaluga_kit/include/bsp/display.h
esp32_s3_eye/esp32_s3_eye.c
esp32_s3_eye/idf_component.yml
esp32_s3_eye/include/bsp/display.h
esp32_s3_korvo_2/esp32_s3_korvo_2.c
esp32_s3_korvo_2/idf_component.yml
esp32_s3_korvo_2/include/bsp/display.h
esp32_s3_korvo_2/include/bsp/touch.h
esp32_s3_usb_otg/esp32_s3_usb_otg.c
esp32_s3_usb_otg/idf_component.yml
esp32_s3_usb_otg/include/bsp/display.h
esp_wrover_kit/esp_wrover_kit.c
esp_wrover_kit/idf_component.yml
esp_wrover_kit/include/bsp/display.h

After discussion, there should be way, how to change the draw buffer size in bsp. This is the solution.

bsp: Allow to change size of the draw buffer

---

examples/audio/main/bsp_audio_example.c

After last changes with LCD screen on Korvo-2 board I made a mistake with buttons. This is the fix in the audio example.

example: Fix buttons in audio example for Korvo-2 board

---

.github/workflows/build_example.yml
.github/workflows/build_test.yml
esp-box/Kconfig
esp-box/esp-box.c
esp-box/idf_component.yml
esp-box/include/bsp/esp-box.h
esp-box/include/bsp/esp-bsp.h
examples/display_audio_photo/main/idf_component.yml

Box/idf v4.4

---

esp-box-lite/idf_component.yml
esp-box-lite/include/bsp/esp-box-lite.h
esp-box/idf_component.yml
esp-box/include/bsp/esp-box.h
examples/display_audio_photo/main/app_disp_fs.c
examples/display_audio_photo/main/bsp_espbox_disp_example.c

example: Use SPIFFS init from BSP

---

.github/workflows/build_example.yml
.idf_build_apps.toml
esp32_s3_korvo_2/CMakeLists.txt
esp32_s3_korvo_2/Kconfig
esp32_s3_korvo_2/esp32_s3_korvo_2.c
esp32_s3_korvo_2/idf_component.yml
esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
examples/audio/main/bsp_audio_example.c
examples/audio/partitions.csv
examples/bsp_ext.py

Example: Update audio example for esp_codec_dev component

---

.build-test-rules.yml
esp-box-lite/CMakeLists.txt
esp-box-lite/esp-box-lite.c
esp-box-lite/esp-box-lite_idf4.c
esp-box-lite/esp-box-lite_idf5.c
esp-box-lite/idf_component.yml
esp-box-lite/include/bsp/esp-box-lite.h
esp-box-lite/priv_include/bsp_err_check.h
esp-box/esp-box.c
esp-box/priv_include/bsp_err_check.h
examples/display_audio_photo/main/app_disp_fs.c

- Added support for IDF v4.4 into ESP-BOX-Lite
- New API for display init with configuration

bsp: Added support for IDF v4.4 into ESP-BOX-Lite

---

components/lcd_touch/esp_lcd_touch/Kconfig
components/lcd_touch/esp_lcd_touch/README.md
components/lcd_touch/esp_lcd_touch/esp_lcd_touch.c
components/lcd_touch/esp_lcd_touch/idf_component.yml
components/lcd_touch/esp_lcd_touch/include/esp_lcd_touch.h

esp_lcd_touch add sleep mode interface.

esp_lcd_touch: add low power interface. (BSP-374)

---

components/esp_lvgl_port/esp_lvgl_port.c
components/esp_lvgl_port/idf_component.yml
components/esp_lvgl_port/include/esp_lvgl_port.h

esp_lvgl_port: add low power interface. (BSP-371)

---

.build-test-rules.yml
esp_wrover_kit/CMakeLists.txt
esp_wrover_kit/Kconfig
esp_wrover_kit/esp_wrover_kit.c
esp_wrover_kit/idf_component.yml
esp_wrover_kit/include/bsp/esp_wrover_kit.h
esp_wrover_kit/priv_include/bsp_err_check.h

Updated ESP-WROVER-KIT with new BSP API
- Added some missing APIs (e.g. SPIFFS)
- Updated some old APIs (e.g. buttons)
- Updated LCD API

bsp: Update new API for buttons and display

---

esp-box/esp-box.c
esp-box/idf_component.yml
esp32_s3_eye/esp32_s3_eye.c
esp32_s3_eye/idf_component.yml

i2c: Fixed i2c init.

---

components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
components/lcd_touch/esp_lcd_touch_gt911/include/esp_lcd_touch_gt911.h

- Add low-power interfaces.
- Add multiple Addr options.

lcd_touch_gt911: Add low_power interface and button. (BSP-380)

---

bsp/esp32_s3_eye/idf_component.yml

Quick fix for private dependency `esp_lvgl_port`

fix(s3_eye): Make esp_lvgl_port dependency public

---

components/lcd_touch/esp_lcd_touch/esp_lcd_touch.c
components/lcd_touch/esp_lcd_touch/idf_component.yml
components/lcd_touch/esp_lcd_touch/include/esp_lcd_touch.h

* Add a new parameter `user_data` in configurations.
* Add a new API to register the interrupt with `user_data`

lcd_touch: add ISR user_data

---

bsp/esp32_s3_usb_otg/CMakeLists.txt
bsp/esp32_s3_usb_otg/Kconfig
bsp/esp32_s3_usb_otg/esp32_s3_usb_otg.c
bsp/esp32_s3_usb_otg/esp32_s3_usb_otg_idf4.c
bsp/esp32_s3_usb_otg/esp32_s3_usb_otg_idf5.c
bsp/esp32_s3_usb_otg/idf_component.yml
bsp/esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h

bsp: Added support for IDF v4.4 into ESP32-S3-USB-OTG

---

bsp/esp-box-3/esp-box-3.c
bsp/esp-box-3/idf_component.yml
bsp/esp-box-lite/idf_component.yml
bsp/esp-box/Kconfig
bsp/esp-box/idf_component.yml

- use vendor_config to update LCD driver of ILI9341.
- update button version to use lastest feature.

Feature/update box3 lcd driver (BSP-415)

---

bsp/esp32_azure_iot_kit/idf_component.yml
bsp/esp32_c3_lcdkit/idf_component.yml
bsp/esp32_lyrat/idf_component.yml
bsp/esp32_s2_kaluga_kit/idf_component.yml
bsp/esp32_s3_eye/idf_component.yml
bsp/esp32_s3_korvo_1/idf_component.yml
bsp/esp32_s3_korvo_2/idf_component.yml
bsp/esp32_s3_lcd_ev_board/idf_component.yml
bsp/esp32_s3_usb_otg/idf_component.yml
bsp/esp_bsp_generic/idf_component.yml
bsp/esp_wrover_kit/idf_component.yml

Allow to use latest version of button and led_indicator component for fix compilation errors and warnings after changes in IDF master.

button: Fix button component version in all BSPs.

---

BSP_development_guide.md
CONTRIBUTING.md

feature: Add development guide

---

.github/workflows/upload_component.yml
components/lcd/esp_lcd_ili9881c/CMakeLists.txt
components/lcd/esp_lcd_ili9881c/README.md
components/lcd/esp_lcd_ili9881c/esp_lcd_ili9881c.c
components/lcd/esp_lcd_ili9881c/idf_component.yml
components/lcd/esp_lcd_ili9881c/include/esp_lcd_ili9881c.h
components/lcd/esp_lcd_ili9881c/license.txt
test_app/CMakeLists.txt

feat(lcd): add ili9881c driver (BSP-431)

---

components/esp_lvgl_port/README.md
components/esp_lvgl_port/esp_lvgl_port.c
components/esp_lvgl_port/idf_component.yml
components/esp_lvgl_port/include/esp_lvgl_port.h

1: add sw rotate.
2: add sram copy form PSRAM.

esp_lvgl_port: add sw_rotate and psram to sram. (BSP-417)

---

bsp/esp_bsp_generic/idf_component.yml
bsp/esp_bsp_generic/src/esp_bsp_generic.c

Fixed build issue after changed led_indicator.

bsp: Fixed generic led_indicator

---

.github/pull_request_template.md

Creating PR template (BSP-490)

---

components/esp_lvgl_port/CHANGELOG.md
components/esp_lvgl_port/idf_component.yml
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port.c
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port_disp.c
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port_usbhid.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_usbhid.c

- Added missing includes
- Fixed watchdog error in some cases in LVGL9

fix(lvgl_port): Fixed missing headers.

---

components/esp_lvgl_port/CHANGELOG.md
components/esp_lvgl_port/idf_component.yml
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port_disp.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
examples/display/main/idf_component.yml
examples/generic_button_led/main/idf_component.yml

Fixed missing callback in IDF4.4.3 and lower for LVGL port

fix(esp_lvgl_port): Fixed missing callback in IDF4.4.3 and lower

---

.github/ISSUE_TEMPLATE/02_Issue-Report.yml

JIRA issue type fix from Task to Bug

Update correct JIRA issue type (BSP-522)

---

components/mpu6050/README.md

Fixed bad link to example for MPU6050

mpu6050: Update readme - example link

---

bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
bsp/esp32_p4_function_ev_board/idf_component.yml

Fixed SD card initialization on ESP32-P4

fix: Fixed SD card initialization on ESP32-P4 BSP

---

.github/ci/bsp_noglib.py
.github/workflows/build-examples-gh-pages-on-push.yml
.github/workflows/build_example.yml
.github/workflows/upload_component_noglib.yml

Fix idf-component-version to 1.*. 
Version 2.* was released today and it is not compatible

fix(ci): Use fixed version of idf-component-manager

---

.github/workflows/build-examples-gh-pages-on-push.yml

Updated IDF version for launchpad builds to v5.3

Update IDF version for launchpad builds to v5.3

---

bsp/esp32_p4_function_ev_board/README.md

Closes https://github.com/espressif/esp-bsp/issues/379

docs(esp32_p4_devboard): Fix LCD resolution in readme

---

.pre-commit-config.yaml

Unblocks https://github.com/espressif/esp-bsp/pull/407

fix(pre-commit): Run README check only for files in BSP root folder

---

CONTRIBUTING.md
components/esp_lvgl_port/CHANGELOG.md
components/esp_lvgl_port/docs/performance.md
components/esp_lvgl_port/idf_component.yml
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c

- Updated performance documentation for LVGL9
- Updated handling RGB flush in LVGL9

doc(LVGL port): Updated performance documentation for LVGL9 

---

.github/workflows/build-applications.yml

esp-idf master branch now points to v5.5. Add release/v5.4 build

feat(ci): Add build for release/v5.4

---

examples/audio/README.md

Updates the documented record time to match the new sample parameters.
Follow up to https://github.com/espressif/esp-bsp/pull/175

examples: audio: update documented record time (BSP-509)

---

components/lcd/esp_lcd_ili9881c/esp_lcd_ili9881c.c
components/lcd/esp_lcd_ili9881c/idf_component.yml
components/lcd/esp_lcd_st7796/esp_lcd_st7796_mipi.c
components/lcd/esp_lcd_st7796/idf_component.yml
components/lcd/esp_lcd_st7796/include/esp_lcd_st7796.h

Fixed the issue of some components having an excessively low Lane bit rate and resolved several known issues.

bugfix(lcd): Fixed low Lane bit rate and other known issues. (BSP-579)

---

.github/workflows/upload_component.yml

- Add LT8912B into upload component

fix(hdmi): Add LT8912B into upload component

---

README.md

Closes https://github.com/espressif/esp-bsp/issues/456

docs: Move deprecated BSPs to deprecated section

---

.github/workflows/build-run-applications.yml
conftest.py
examples/generic_button_led/pytest_generic_button_led.py
examples/generic_button_led/sdkconfig.bsp.esp_bsp_devkit
examples/generic_button_led/sdkconfig.bsp.esp_bsp_generic
pytest.ini

- Add DevKit tu BSP Runner Wall for testing devkit/generic BSP

ci(runner): Add devkit to BSP Runner Wall

---

components/esp_lvgl_port/CHANGELOG.md
components/esp_lvgl_port/README.md
components/esp_lvgl_port/include/esp_lvgl_port_button.h
components/esp_lvgl_port/include/esp_lvgl_port_knob.h
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port_button.c
components/esp_lvgl_port/src/lvgl8/esp_lvgl_port_knob.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_button.c
components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_knob.c

- Updated LVGL port for using it with button component v4
Closes https://github.com/espressif/esp-bsp/issues/494

feat(lvgl_port): Update LVGL port for using button v4

---

.github/workflows/build-run-applications.yml

- Sorry for issue CI when pushed to master

ci(runner): Fixed build and run CI when push to master

---

components/lcd/esp_lcd_gc9a01/idf_component.yml
components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h

- Fixed compilation error in IDF5.1

fix(esp_lcd_gc9a01): Fix compilation error in IDF5.1

---

components/lcd/esp_lcd_st7796/idf_component.yml

esp_lcd_st7796 also works on esp32

esp_lcd_st7796 also works on esp32 (BSP-647)

---

bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
bsp/esp32_p4_function_ev_board/idf_component.yml

* Failing pedantic build https://github.com/espressif/idf-extra-components/actions/runs/13895330763/job/38874653880
* Introduced in https://github.com/espressif/esp-bsp/pull/507

fix(p4_ev_board): Fix pedantic build

---

components/esp_lvgl_port/include/esp_lvgl_port_disp.h

Fix typo in comment (BSP-658)

---

components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml

- Fixed button issue
Closes #331 
Closes #518

fix(gt911): Fixed reading buttons and changed warning log

---

.github/workflows/squareline.yml

ci(squareline): Fixed upload-artifact v3 issue

---

.github/workflows/upload_component_noglib.yml
bsp/esp-box-3/esp-box-3.c
bsp/esp-box-3/include/bsp/config.h
bsp/esp-box-3/include/bsp/esp-box-3.h

Related to #534 (Cannot be closed, it is related to another board)

bsp(esp-box-3): Add support for noglib.

---

.github/workflows/squareline.yml

I am sorry, my fault. I overlooked download-artifact component :-(

ci(squareline): Fixed download-artifact v3 issue

---

components/ds18b20/examples/ds18b20-read/main/ds18b20-read.c
components/ds18b20/include/ds18b20.h
components/ds18b20/src/ds18b20.c

Closes https://github.com/espressif/esp-bsp/issues/323

feat(ds18b20): add a interface to get device address (BSP-665)

---

components/io_expander/esp_io_expander_tca9554/esp_io_expander_tca9554.c
components/io_expander/esp_io_expander_tca9554/idf_component.yml

fix a memory leak when a device fails to reset. (BSP-670)

---

SquareLine/README.md
SquareLine/boards/v9/esp32_c3_lcdkit/manifest.json
SquareLine/boards/v9/esp32_s2_kaluga_kit/manifest.json
SquareLine/boards/v9/esp32_s3_eye/manifest.json
SquareLine/boards/v9/esp32_s3_korvo_2/manifest.json
SquareLine/boards/v9/esp32_s3_lcd_ev_board/manifest.json
SquareLine/boards/v9/esp32_s3_usb_otg/manifest.json
SquareLine/boards/v9/espbox/manifest.json
SquareLine/boards/v9/espbox_3/manifest.json
SquareLine/boards/v9/espbox_lite/manifest.json
SquareLine/boards/v9/espwroverkit/manifest.json
SquareLine/boards/v9/m5_atom_s3/manifest.json
SquareLine/boards/v9/m5dial/manifest.json
SquareLine/boards/v9/m5stack_core_2/manifest.json
SquareLine/boards/v9/m5stack_core_s3/manifest.json

Squareline support LVGL version 9.1 and 9.2. Add 9.2 to the list of supported versions

feat: Add LVGL9.2 support to Squareline packages

---

.github/ci/bsp_example_update.py
.github/workflows/upload_component.yml
bsp/esp-box-3/README.md
bsp/esp-box-3/idf_component.yml
bsp/esp32_c3_lcdkit/idf_component.yml
bsp/esp32_lyrat/idf_component.yml
bsp/esp32_p4_function_ev_board/README.md
bsp/esp32_p4_function_ev_board/idf_component.yml
bsp/esp32_s2_kaluga_kit/idf_component.yml
bsp/esp32_s3_eye/README.md
bsp/esp32_s3_eye/idf_component.yml
bsp/esp32_s3_korvo_1/idf_component.yml
bsp/esp32_s3_korvo_2/idf_component.yml
bsp/esp32_s3_lcd_ev_board/README.md
bsp/esp32_s3_lcd_ev_board/idf_component.yml
bsp/esp32_s3_usb_otg/idf_component.yml
bsp/m5_atom_s3/idf_component.yml
bsp/m5dial/README.md
bsp/m5dial/idf_component.yml
bsp/m5stack_core/idf_component.yml
bsp/m5stack_core_2/idf_component.yml
bsp/m5stack_core_s3/README.md
bsp/m5stack_core_s3/idf_component.yml

- Allow to add one example to multiple BSPs 
- it will change YML for specific BSP 
- it will copy specific `sdkconfig.bsp.`* to `sdkconfig.defaults`

ci(component_upload): Upload all examples to each BSP with right YML files.

---

bsp/esp-box-3/README.md
bsp/esp32_p4_function_ev_board/README.md
bsp/esp32_s3_eye/README.md
bsp/esp32_s3_korvo_2/API.md
bsp/esp32_s3_korvo_2/idf_component.yml
bsp/esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
bsp/esp32_s3_lcd_ev_board/README.md
bsp/m5dial/README.md
bsp/m5stack_core_s3/README.md

fix(bsp): Fix inverted LED pin numbers for Korvo2

---

components/lcd/.build-test-rules.yml
components/lcd/esp_lcd_gc9503/test_apps/main/idf_component.yml
components/lcd/esp_lcd_gc9503/test_apps/main/test_esp_lcd_gc9503.c
components/lcd/esp_lcd_ili9881c/test_apps/main/test_esp_lcd_ili9881c.c
components/lcd/esp_lcd_st7796/test_apps/main/test_esp_lcd_st7796_mipi.c

- Migrate/fix unit tests in LCDs to I2C driver-NG

feat(lcd): Migrate/fix unit tests to I2C driver-NG

---

.github/ci/bsp_noglib.py
.github/ci/update_supported_boards.py
bsp/esp32_s3_lcd_ev_board/README.md
bsp/esp32_s3_lcd_ev_board/idf_component.yml

- Remove examples in noglib
- Release last fixes in ESP32-S3-LCD-EV-Board

ci(noglib): Remove examples in noglib
