- esp32_azure_iot_kit/idf_component.yml
- esp32_s2_kaluga_kit/idf_component.yml
- esp_wrover_kit/idf_component.yml
These URLs can be shown in the UI, also it will be simpler to find the source of the component.
The question is, whether we should point to the root of the repo, or to the component directory inside
> Add URLs to component manifests

- components/bh1750/CMakeLists.txt
- components/bh1750/idf_component.yml
- components/es8311/CMakeLists.txt
- components/es8311/idf_component.yml
- components/fbm320/CMakeLists.txt
- components/fbm320/idf_component.yml
- components/hts221/CMakeLists.txt
- components/hts221/idf_component.yml
- components/mag3110/CMakeLists.txt
- components/mpu6050/CMakeLists.txt
- components/mpu6050/idf_component.yml
- components/ssd1306/CMakeLists.txt
- components/ssd1306/idf_component.yml
Currently, `esp-bsp` components rely on IDF's `components/{target}` to retrieve `driver` component:
```
REQUIRES                REQUIRES
es8311 ----------------> esp32 ----------------> driver
```  
So, when `{target}` component will stop depending on `driver` component, `es8311` and all other components will fail to build.
This PR add an explicit `REQUIRES` to avoid this issue in the future.
> Components: explicit the depencies on "driver" component

- components/es8311/es8311.c
- components/es8311/idf_component.yml
- components/es8311/include/es8311.h
- test_app/CMakeLists.txt
Notable changes:
- Version bumped to 1.0.0 (first stable API)
- There is no DAC ramp-up setup during initialization
- Ramp-ups for ADC and DAC are now configurable through dedicated API
- ES8311 can accepts MCLK signal from both MCLK pin (user must define its frequency) and SCK  pin
> ES8311: release 1.0.0

- components/mag3110/idf_component.yml
Mag3110 version was not bumped in #15
> mag3110: Bump version

- .github/workflows/build_example.yml
- examples/display/main/idf_component.yml
- examples/display_audio/main/idf_component.yml
- examples/mqtt_example/main/idf_component.yml
- examples/rainmaker_example/main/idf_component.yml
- examples/sensors_example/main/idf_component.yml
- examples/touchscreen_colorwheel/main/idf_component.yml
By using local components in examples, we make sure that we compile actual code from the specific PR (rather than already uploaded component in the component service)
> ci: Override path for BSPs in examples

- components/esp_jpeg/Kconfig
- components/esp_jpeg/idf_component.yml
I forgot to add esp32c2 to Kconfig, that there is not tjpgd in ROM code. Fixed now.
> esp_jpeg: Fixed unsupported MCU of tjpgd in ROM.

- components/lcd/esp_lcd_gc9a01/esp_lcd_gc9a01.c
- components/lcd/esp_lcd_gc9a01/idf_component.yml
- components/lcd/esp_lcd_ili9341/esp_lcd_ili9341.c
- components/lcd/esp_lcd_ili9341/idf_component.yml
After morris found and fixed this issue in IDF, here is fix for other LCD components.
> lcd: fix wrong bpp size of rgb666 format

- .github/workflows/upload_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_gt1151/README.md
- components/lcd_touch/esp_lcd_touch_gt1151/esp_lcd_touch_gt1151.c
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/include/esp_lcd_touch_gt1151.h
- components/lcd_touch/esp_lcd_touch_gt1151/license.txt
Add a new touch controller named GT1151 into the components. It's one of the peripherals of ESP32-S3-LCD-EV-BOARD.
> Add GT1151 touch controller into components (BSP-210)

- esp32_s2_kaluga_kit/idf_component.yml
- esp32_s2_kaluga_kit/include/bsp/esp32_s2_kaluga_kit.h
- esp32_s3_eye/esp32_s3_eye.c
- esp32_s3_eye/idf_component.yml
- esp32_s3_eye/include/bsp/esp32_s3_eye.h
- Extend s3-eye BSP with Microphone settings. There is no example yet. We plan to reuse one of the already implemented examples.
- Update BSPs (kaluga and s3-eye) for [esp32-camera v2.0.2](https://github.com/espressif/esp32-camera/releases/tag/v2.0.2). It allows us to use already initialized I2C.
> S3-EYE: Microphone support

- .github/workflows/upload_component.yml
- components/io_expander/esp_io_expander_tca9554/CMakeLists.txt
- components/io_expander/esp_io_expander_tca9554/README.md
- components/io_expander/esp_io_expander_tca9554/esp_io_expander_tca9554.c
- components/io_expander/esp_io_expander_tca9554/idf_component.yml
- components/io_expander/esp_io_expander_tca9554/include/esp_io_expander_tca9554.h
- components/io_expander/esp_io_expander_tca9554/license.txt
This new component is based on "esp_io_expander" main component. And it's one of the peripherals in the ESP32-S3-LCD-EV-BOARD Development Board.
> add new io_expander chip - tca9554

- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/include/esp_lvgl_port.h
This is necessary to fix C++ usage:
```
In file included from Esp32OlcbLcd/main/display.cpp:16:
Esp32OlcbLcd/main/display.cpp: In function 'void initialize_display()':
Esp32OlcbLcd/managed_components/espressif__esp_lvgl_port/include/esp_lvgl_port.h:74:5: warning: missing initializer for member 'lvgl_port_cfg_t::task_affinity' [-Wmissing-field-initializers]
74 |     }
|     ^
Esp32OlcbLcd/main/display.cpp:245:41: note: in expansion of macro 'ESP_LVGL_PORT_INIT_CONFIG'
245 |     const lvgl_port_cfg_t lvgl_config = ESP_LVGL_PORT_INIT_CONFIG();
|                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
managed_components/espressif__esp_lvgl_port/include/esp_lvgl_port.h:74:5: error: designator order for field 'lvgl_port_cfg_t::task_affinity' does not match declaration order in 'const …
```
> Reorder initializers to match struct (BSP-228)

- components/lcd/esp_lcd_ili9341/esp_lcd_ili9341.c
- components/lcd/esp_lcd_ili9341/idf_component.yml
Fixed color setting in ILI9341 LCD component. 
It is fix for this issue: https://github.com/espressif/esp-idf/issues/10242
> lcd: ILI9341 color fix

- components/io_expander/esp_io_expander_tca9554/README.md
- components/io_expander/esp_io_expander_tca9554/idf_component.yml
- components/io_expander/esp_io_expander_tca9554/include/esp_io_expander_tca9554.h
Added I2C addresses for TCA9554A into header file.
> tca9554: Added I2C addresses for A version of the expander.

- components/lcd_touch/esp_lcd_touch/idf_component.yml
- components/lcd_touch/esp_lcd_touch/include/esp_lcd_touch.h
- esp32_s2_kaluga_kit/esp32_s2_kaluga_kit.c
- esp32_s2_kaluga_kit/idf_component.yml
- esp32_s3_eye/esp32_s3_eye.c
- esp32_s3_eye/idf_component.yml
Fix for issue #87. 
Fixed ADC channel constants after iot_button updated to ADC NG driver (compatible with IDF5.0).
> lcd_touch: Add FreeRTOS includes into header file.

- components/lcd_touch/esp_lcd_touch_tt21100/README.md
Just a quick fix in readme.md document about the example call to esp_lcd_touch_get_coordinates().
> lcd_touch_tt21100: Fixes  esp_lcd_touch_get_coordinates() arg in README.md (BSP-243)

- esp-box/Kconfig
- esp-box/esp-box.c
- esp-box/idf_component.yml
Partially close #106, since the BSP for esp-box is needed at the first stage. If some modifications are needed, please update and commit directly.
> bsp: Use esp_lvgl_port for esp-box bsp (BSP-242)

- esp-box/CMakeLists.txt
- esp-box/Kconfig
- esp-box/esp-box.c
- esp-box/idf_component.yml
- esp-box/include/bsp/esp-box.h
Just a quick port from https://github.com/espressif/esp-box/blob/master/components/bsp/src/storage/bsp_spiffs.c, since espressif/esp-box will totally use the esp-box bsp from esp-bsp. Closes #107 .
> bsp: Support to mount spiffs for esp-box bsp (BSP-245)

- README.md
- esp-box/idf_component.yml
- esp32_azure_iot_kit/idf_component.yml
- esp32_s2_kaluga_kit/idf_component.yml
- esp32_s2_kaluga_kit/include/bsp/esp32_s2_kaluga_kit.h
- esp32_s3_lcd_ev_board/idf_component.yml
- esp_wrover_kit/idf_component.yml
Latest idf-component-manager release allows us to upload examples with the SW package.
All BSPs with example now use this feature.
> BSP: Add examples to component manifest files

- components/mpu6050/README.md
- components/mpu6050/idf_component.yml
- components/mpu6050/include/mpu6050.h
- components/mpu6050/mpu6050.c
- Include new functions to setup and enable interrupts produced by the MPU6050 on different events (mainly `DATA_READY` at the moment, see notes below).
- Add new definitions for registers, types and enumerations used to configure and handle interrupts triggered by the MPU6050.
- Update component README.md with more information about the sensor, mention ISR support and add links to the register map and the sensors example.
Since the driver does not yet support FiFo or I2C sensor slaves, interrupts by `FIFO_OVERFLOW` and `I2C_MST_INT` are not produced by the MPU6050. If necessary, these driver features could be implemented in the future. 
I decided not to include `MOTION_DETECT` interrupt support yet, because there is conflicting information on this feature from different MPU6050 register …
> Add MPU6050 ISR support (BSP-251)

- components/esp_lvgl_port/esp_lvgl_port.c
- components/esp_lvgl_port/idf_component.yml
LVGL and external user event will operate the same API, `lvgl_port_lock` is used to protect this API.
When lvgl event calls this kind of API, it will cause a secondary lock, cause deadlock.
> esp_lvgl_port: lvgl_port_lock deadlock (BSP-249)

- components/lcd_touch/esp_lcd_touch_gt1151/esp_lcd_touch_gt1151.c
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/esp_lcd_touch_stmpe610.c
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/esp_lcd_touch_tt21100.c
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
The description of `levels.reset` flag in `esp_lcd_touch_config_t` is "Level of reset pin in reset", but all lcd_touch components (like gt911, gt1151... ) act in the opposite way.
> lcd_touch: fix the reset level reversal bug

- esp32_s3_korvo_2/Kconfig
- esp32_s3_korvo_2/esp32_s3_korvo_2.c
- esp32_s3_korvo_2/idf_component.yml
- esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
- esp32_s3_korvo_2/priv_include/bsp_err_check.h
- examples/display_audio_photo/main/CMakeLists.txt
Added LCD support into Korvo-2 BSP. 
I decided change the audio settings back to mono. 
Tested with:
- display_rotation
- display_camera
- display_audio_photo
> bsp: Added LCD support into ESP32-S3-Korvo-2 Board Support Package

- components/esp_lvgl_port/esp_lvgl_port.c
- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/include/esp_lvgl_port.h
Added public for esp_lcd_touch in esp_lvgl_port for using LCD touch header outside.
> esp_lvgl_port: Add public for esp_lcd_touch

- components/esp_lvgl_port/esp_lvgl_port.c
- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/include/esp_lvgl_port.h
There is another minor change in LVGL port, which we need for `esp32_s3_eye` BSP. We need to not sleep during the LVGL task. I added a maximum time in ms, for which the task can sleep.
> esp_lvgl_port: Add maximum time in ms for sleep LVGL task.

- .github/workflows/upload_component.yml
- components/lcd_touch/esp_lcd_touch_cst816s/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_cst816s/README.md
- components/lcd_touch/esp_lcd_touch_cst816s/esp_lcd_touch_cst816s.c
- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_cst816s/include/esp_lcd_touch_cst816s.h
- components/lcd_touch/esp_lcd_touch_cst816s/license.txt
- components/lcd_touch/esp_lcd_touch_ft5x06/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_ft5x06/README.md
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_gt1151/README.md
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_stmpe610/README.md
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/CMakeLists.txt
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
I have adapted a new touch chip for customers and want to store it in the components manager to provide convenience for other customers.
> lcd_touch: add new component CST816S

- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
Some types from esp_lcd_touch is used and this component must be as public in all touch components.
> lcd_touch: Add pulbic for all touch components.

- components/esp_lvgl_port/CMakeLists.txt
- components/esp_lvgl_port/README.md
- components/esp_lvgl_port/esp_lvgl_port.c
- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/include/esp_lvgl_port.h
I am working on BSP for ESP-BOX-Lite and this board hasn't got touch screen. I decided for use the buttons for control LVGL objects and the best place for handling is LVGL port component. Here is my implementation.
> esp_lvgl_port: Add support for buttons as a input device.

- esp-box/CMakeLists.txt
- esp-box/esp-box.c
- esp-box/idf_component.yml
- esp-box/include/bsp/display.h
- esp32_s2_kaluga_kit/CMakeLists.txt
- esp32_s2_kaluga_kit/esp32_s2_kaluga_kit.c
- esp32_s2_kaluga_kit/idf_component.yml
- esp32_s2_kaluga_kit/include/bsp/display.h
- esp32_s3_eye/CMakeLists.txt
- esp32_s3_eye/esp32_s3_eye.c
- esp32_s3_eye/idf_component.yml
- esp32_s3_eye/include/bsp/display.h
- esp32_s3_korvo_2/CMakeLists.txt
- esp32_s3_korvo_2/esp32_s3_korvo_2.c
- esp32_s3_korvo_2/idf_component.yml
- esp32_s3_korvo_2/include/bsp/display.h
- esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
- esp32_s3_usb_otg/CMakeLists.txt
- esp32_s3_usb_otg/esp32_s3_usb_otg.c
- esp32_s3_usb_otg/idf_component.yml
- esp32_s3_usb_otg/include/bsp/display.h
- esp_wrover_kit/CMakeLists.txt
- esp_wrover_kit/esp_wrover_kit.c
- esp_wrover_kit/idf_component.yml
- esp_wrover_kit/include/bsp/display.h
- esp_wrover_kit/include/bsp/esp_wrover_kit.h
This PR allows LCD initialization without LVGL. The API is in a separate file `bsp/lcd.h` to indicate that it is not needed in usual usacases.
I'd like to discuss few issues before I implement it for all BSPs:
1. Is it OK (at least for now) to omit the deinit functions? _EDIT:_  Seems to be OK for now
2. ~Should we extend the backlight_init function with variable LEDC channels and timers? (the user can, after all, implement his own backlight control)~ 
Any ideas welcome!
Related #121
> bsp: Proposal of LCD API

- esp-box/esp-box.c
- esp-box/idf_component.yml
- esp-box/include/bsp/display.h
- esp-box/include/bsp/esp-box.h
- esp-box/include/bsp/touch.h
- esp32_s2_kaluga_kit/esp32_s2_kaluga_kit.c
- esp32_s2_kaluga_kit/idf_component.yml
- esp32_s2_kaluga_kit/include/bsp/display.h
- esp32_s2_kaluga_kit/include/bsp/esp32_s2_kaluga_kit.h
- esp32_s3_eye/esp32_s3_eye.c
- esp32_s3_eye/idf_component.yml
- esp32_s3_eye/include/bsp/display.h
- esp32_s3_eye/include/bsp/esp32_s3_eye.h
- esp32_s3_korvo_2/esp32_s3_korvo_2.c
- esp32_s3_korvo_2/idf_component.yml
- esp32_s3_korvo_2/include/bsp/display.h
- esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
- esp32_s3_korvo_2/include/bsp/touch.h
- esp32_s3_usb_otg/esp32_s3_usb_otg.c
- esp32_s3_usb_otg/idf_component.yml
- esp32_s3_usb_otg/include/bsp/display.h
- esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h
- esp_wrover_kit/esp_wrover_kit.c
- esp_wrover_kit/idf_component.yml
- esp_wrover_kit/include/bsp/display.h
- esp_wrover_kit/include/bsp/esp_wrover_kit.h
Fixed display and touch headers for using with C++ and updated BSP header with LCD constants.
Closes #143, #144, #145
> bsp: Fix display headers for use in C++ and update BSP constants

- components/lcd_touch/esp_lcd_touch/README.md
- components/lcd_touch/esp_lcd_touch/esp_lcd_touch.c
- components/lcd_touch/esp_lcd_touch/idf_component.yml
- components/lcd_touch/esp_lcd_touch/include/esp_lcd_touch.h
- components/lcd_touch/esp_lcd_touch_cst816s/esp_lcd_touch_cst816s.c
- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_ft5x06/esp_lcd_touch_ft5x06.c
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/esp_lcd_touch_gt1151.c
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/esp_lcd_touch_stmpe610.c
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/esp_lcd_touch_tt21100.c
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
Improved esp_lcd_touch: Added support for interrupt callback. It can be registered when initializing or later (later is for LVGL port for future use).
This feature was requested by Qt developers (BSP-284).
> lcd_touch: Add interrupt callback into esp_lcd_touch

- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
> esp_lcd_touch: Fixed minimum required esp_lcd_touch version.

- .github/workflows/upload_component.yml
- components/ds18b20/CHANGELOG.md
- components/ds18b20/CMakeLists.txt
- components/ds18b20/LICENSE
- components/ds18b20/README.md
- components/ds18b20/idf_component.yml
- components/ds18b20/include/ds18b20.h
- components/ds18b20/include/ds18b20_types.h
- components/ds18b20/src/ds18b20.c
- test_app/CMakeLists.txt
Added the driver for the DS18B20 temperature sensor.
This is a 1-Wire sensor, so it depends on the [onewire_bus](https://components.espressif.com/components/espressif/onewire_bus) component.
> ds18b20: device driver, work with onewire_bus library (BSP-319)

- components/lcd_touch/esp_lcd_touch_ft5x06/esp_lcd_touch_ft5x06.c
- [master] Version of modified component bumped
There is an error in initializing the reset and interrupt pins for the FT5X06 touch driver, where part of the pins' functionalities were changed.
> fixed initialization of reset and interrupt pins (BSP-321)

- .github/workflows/upload_component.yml
- components/io_expander/esp_io_expander_tca95xx_16bit/CMakeLists.txt
- components/io_expander/esp_io_expander_tca95xx_16bit/README.md
- components/io_expander/esp_io_expander_tca95xx_16bit/esp_io_expander_tca95xx_16bit.c
- components/io_expander/esp_io_expander_tca95xx_16bit/idf_component.yml
- components/io_expander/esp_io_expander_tca95xx_16bit/include/esp_io_expander_tca95xx_16bit.h
- components/io_expander/esp_io_expander_tca95xx_16bit/license.txt
closes #137
Added TCA9539 and TCA9555 16bit port expanders.
> TCA95xx_16bit (BSP-326)

- .github/workflows/upload_component.yml
- components/io_expander/esp_io_expander_ht8574/CMakeLists.txt
- components/io_expander/esp_io_expander_ht8574/README.md
- components/io_expander/esp_io_expander_ht8574/esp_io_expander_ht8574.c
- components/io_expander/esp_io_expander_ht8574/idf_component.yml
- components/io_expander/esp_io_expander_ht8574/include/esp_io_expander_ht8574.h
- components/io_expander/esp_io_expander_ht8574/license.txt
> io_expander: Added io_expander of HT8574. (BSP-280)

- components/lcd_touch/esp_lcd_touch_cst816s/README.md
- components/lcd_touch/esp_lcd_touch_cst816s/esp_lcd_touch_cst816s.c
- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/esp_lcd_touch_stmpe610.c
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
Closes https://github.com/espressif/esp-bsp/issues/178
Fix bugs of `esp_lcd_touch_cst816s`
> CST816: Extend the reset time and fix the interruption

- .idf_build_apps.toml
- .ignore_build_warnings.txt
Ignore pkg_resources warning coming from updated `pip`
> fix(ci): Ignore pkg_resources warning

- esp-box-lite/Kconfig
- esp-box-lite/esp-box-lite.c
- esp-box-lite/idf_component.yml
- esp-box-lite/include/bsp/esp-box-lite.h
- esp-box/Kconfig
- esp-box/esp-box.c
- esp-box/idf_component.yml
- esp-box/include/bsp/esp-box.h
In some scenarios, the remaining SRAM is insufficient, make the num of framebuf height to configurable.
> framebuffer: esp-box/esp-box-lite use framebuf height form Kconfig (BSP-331)

- .build-test-rules.yml
- .github/PULL_REQUEST_TEMPLATE/pr_template_bsp.md
- .github/workflows/build_example.yml
- .idf_build_apps.toml
- esp-box/CMakeLists.txt
- esp-box/esp-box.c
- esp-box/esp-box_idf4.c
- esp-box/esp-box_idf5.c
- esp-box/idf_component.yml
- esp-box/include/bsp/esp-box.h
- examples/bsp_ext.py
- examples/display/main/idf_component.yml
- examples/display_audio_photo/main/app_disp_fs.c
- examples/display_audio_photo/main/idf_component.yml
- examples/display_camera/main/idf_component.yml
- examples/display_lvgl_demos/main/idf_component.yml
- examples/display_rotation/main/idf_component.yml
- Added support for IDF v4.4 into ESP-BOX
- Fixed display_audio_photo example (recording)
- Updated Pull Request template for new BSPs
- Used new API for button handling
- New API for display init with configuration
- Removed minimal IDF version from examples
Closes https://github.com/espressif/esp-bsp/issues/151
> bsp: Added support for IDF v4.4 into ESP-BOX

- esp-box/esp-box.c
- esp-box/idf_component.yml
Iot button call `bsp_get_main_button` too busy, it'll block I2C bus.
> esp-box: Prevent I2C bus form getting stuck. (BSP-377)

- components/lcd_touch/esp_lcd_touch_cst816s/esp_lcd_touch_cst816s.c
- components/lcd_touch/esp_lcd_touch_ft5x06/esp_lcd_touch_ft5x06.c
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/esp_lcd_touch_gt1151.c
- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
- components/lcd_touch/esp_lcd_touch_stmpe610/esp_lcd_touch_stmpe610.c
- components/lcd_touch/esp_lcd_touch_tt21100/esp_lcd_touch_tt21100.c
Fixed missing reset call in `esp_lcd_touch_ft5x06`. 
Fixed interrupt level in all touch drivers.
Closes #211
> lcd_touch_ft5x06: Fixed missing reset.

- esp-box-lite/Kconfig
- esp-box-lite/esp-box-lite.c
- esp-box-lite/idf_component.yml
- esp-box-lite/include/bsp/esp-box-lite.h
Add initialization and definition of IO button in BSP.
I want to provide the same interface as esp-box here.
> esp-box-lite: Add initialization and definition of IO button (BSP-376)

- components/lcd/esp_lcd_gc9503/README.md
- components/lcd/esp_lcd_gc9503/esp_lcd_gc9503.c
- components/lcd/esp_lcd_gc9503/idf_component.yml
- components/lcd/esp_lcd_gc9503/include/esp_lcd_gc9503.h
Add a feature for all LCD drivers that uses `vendor_config` to pass external custom initialization commands.
> esp_lcd: add vendor config

- .github/workflows/build-examples-gh-pages-on-push.yml
This PR adds a workflow for integration with Launchpad. It builds examples according to `.idf_build_apps.toml` and uploads merged binaries and `config.toml` to github-pages
Detailed description of the action can be found [here](https://github.com/espressif/idf-examples-launchpad-ci-action)
If you want to build examples with specific versions, please provide me with the list and I will adjust the workflow accordingly
Follow up PR will feature a button in the README files (after examples are built with the action)
> ci: Add example building workflow for launchpad (BSP-378)

- esp-box-3/esp-box-3.c
- esp-box-3/idf_component.yml
Add new LCD support, use I2C probe to select LCD.
> esp-box-3: add new LCD support (BSP-379)

- README.md
- examples/audio/README.md
- examples/display/README.md
- examples/display_audio_photo/README.md
- examples/display_camera/README.md
- examples/display_lvgl_demos/README.md
- examples/display_rotation/README.md
- examples/display_sensors/README.md
This MR adds Launchpad URLs in Examples README
As discussed before, the only ommited example is MQTT as it requires Kconfig setup of SSID and Password and it does not make sense to have it flashable by Launchpad
> docs: Include Launchpad URLs in Examples README (BSP-386)

- esp-box-3/idf_component.yml
- esp-box-3/include/bsp/esp-box-3.h
- esp-box-lite/idf_component.yml
- esp-box-lite/include/bsp/esp-box-lite.h
- esp-box/idf_component.yml
- esp-box/include/bsp/esp-box.h
- examples/display_rotation/main/main.c
The first must be merged this component #228
Add new API for initialization MotionSensor in ESP-BOX and ESP-BOX-3 (It can be added into ESP-BOX-Lite too, but there is not assembled this controller).
> bsp: Add support of MotionSensor to ESP-BOXes

- .pre-commit-config.yaml
Fixes pre-commit failing with Python 3.12, among other things.
> change(ci): update astyle_py to 1.0.5

- components/lcd/esp_lcd_gc9503/idf_component.yml
- components/lcd/esp_lcd_gc9503/test_apps/main/idf_component.yml
- components/lcd/esp_lcd_gc9a01/README.md
- components/lcd/esp_lcd_gc9a01/esp_lcd_gc9a01.c
- components/lcd/esp_lcd_gc9a01/idf_component.yml
- components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h
- components/lcd/esp_lcd_gc9a01/test_apps/main/test_esp_lcd_gc9a01.c
- components/lcd/esp_lcd_ili9341/README.md
- components/lcd/esp_lcd_ili9341/esp_lcd_ili9341.c
- components/lcd/esp_lcd_ili9341/idf_component.yml
- components/lcd/esp_lcd_ili9341/include/esp_lcd_ili9341.h
- components/lcd/esp_lcd_ili9341/test_apps/main/test_esp_lcd_ili9341.c
- components/lcd/esp_lcd_st7796/README.md
- components/lcd/esp_lcd_st7796/esp_lcd_st7796.c
- components/lcd/esp_lcd_st7796/idf_component.yml
- components/lcd/esp_lcd_st7796/include/esp_lcd_st7796.h
- components/lcd/esp_lcd_st7796/test_apps/main/idf_component.yml
- components/lcd/esp_lcd_st7796/test_apps/main/test_esp_lcd_st7796.c
* replace `rgb_ele_order` with `rgb_endian`
* add more idf version check
* closes #240 
* closes #242
> lcd: fix incompatible feature

- .github/workflows/upload_component.yml
- bsp/esp_bsp_generic/CMakeLists.txt
- bsp/esp_bsp_generic/Kconfig
- bsp/esp_bsp_generic/LICENSE
- bsp/esp_bsp_generic/README.md
- bsp/esp_bsp_generic/idf_component.yml
- bsp/esp_bsp_generic/include/bsp/esp-bsp.h
- bsp/esp_bsp_generic/include/bsp/esp_bsp_generic.h
- bsp/esp_bsp_generic/priv_include/bsp_err_check.h
- bsp/esp_bsp_generic/src/esp_bsp_generic.c
- bsp/esp_bsp_generic/src/led_blink_defaults.c
- examples/bsp_ext.py
- examples/generic_button_led/CMakeLists.txt
- examples/generic_button_led/README.md
- examples/generic_button_led/main/CMakeLists.txt
- examples/generic_button_led/main/idf_component.yml
- examples/generic_button_led/main/main.c
- examples/generic_button_led/partitions.csv
- examples/generic_button_led/sdkconfig.defaults
- examples/generic_button_led/sdkconfig.esp32_devkitc_V4
- examples/generic_button_led/sdkconfig.esp32_s2_devkitm_1
- examples/generic_button_led/sdkconfig.esp32_s3_devkitc_1
- examples/generic_button_led/sdkconfig.esp32_s3_devkitc_1_1
The first draft of generic BSP for discussion. I didn't want to add more things (leds, LCDs, audio), because it will be complicated for review. I suggesting make each part in one PR, what do you think?
> bsp: New generic BSP (spiffs, sdcard, i2c, buttons).

- examples/display_usb_hid/README.md
Documentation update.
Added instructions how to power up USB Host port on ESP32-S3-USB-OTG. Without described change the example does not read values from mouse or keyboard.
> doc: add ESP32-S3-USB-OTG instructions to power up USB Host (BSP-426)

- bsp/esp_bsp_generic/Kconfig
- bsp/esp_bsp_generic/README.md
- bsp/esp_bsp_generic/idf_component.yml
- bsp/esp_bsp_generic/include/bsp/display.h
- bsp/esp_bsp_generic/include/bsp/esp_bsp_generic.h
- bsp/esp_bsp_generic/include/bsp/touch.h
- bsp/esp_bsp_generic/src/esp_bsp_generic.c
- examples/generic_button_led/README.md
- examples/generic_button_led/sdkconfig.esp32_c2_devkitm_1
- Updated `led_indicator` and support classic RGB LED (e.g. ESP32C2)
- Added LCD and touch support to generig BSP. I selected only some drivers
- LCD is supported only via SPI
- Touch is supported only via I2C
- When some part not used (e.g. buttons, leds, LCD, touch), the component is still downloaded
- Components for all touches and LCDs are downloaded
> bsp: Add display and touch support to gerenic BSP.

- components/lcd/esp_lcd_ili9341/esp_lcd_ili9341.c
- components/lcd/esp_lcd_st7796/esp_lcd_st7796.c
- components/lcd/esp_lcd_st7796/test_apps/main/test_esp_lcd_st7796.c
* ili9341 & st7796: remove unused structs
* st7796: fix the building error of test_apps when using esp32s2
> lcd: remove unused structs

- components/esp_lvgl_port/esp_lvgl_port.c
The `lvgl_port_deinit()` method appears to have an incorrect if-condition when checking if the LVGL task is running. Currently the code essentially says `if (!running) running = false;`, but it should be `if (running) running = false;`. The incorrect condition causes the LVGL task to never be stopped.
> esp_lvgl_port: Fix bad condition in port deinit (BSP-440)

- components/ds18b20/CHANGELOG.md
- components/ds18b20/idf_component.yml
- components/ds18b20/src/ds18b20.c
because of the drop in the sign when doing the temperature conversion
Closes https://github.com/espressif/esp-bsp/issues/258
> fix(ds18b20): fix the wrong value of a sub-zero temperature (BSP-444)

- .github/workflows/build-examples-gh-pages-on-push.yml
Bumped version of Github Action for building examples for ESP Launchpad - fixes the crash in CI.
> fix: Failing CI for Launchpad (BSP-449)

- bsp/esp-box-3/include/bsp/display.h
- bsp/esp-box-3/include/bsp/esp-box-3.h
- bsp/esp-box-lite/include/bsp/display.h
- bsp/esp-box-lite/include/bsp/esp-box-lite.h
- bsp/esp-box/include/bsp/display.h
- bsp/esp-box/include/bsp/esp-box.h
- bsp/esp32_azure_iot_kit/include/bsp/display.h
- bsp/esp32_azure_iot_kit/include/bsp/esp32_azure_iot_kit.h
- bsp/esp32_c3_lcdkit/include/bsp/display.h
- bsp/esp32_c3_lcdkit/include/bsp/esp32_c3_lcdkit.h
- bsp/esp32_s2_kaluga_kit/esp32_s2_kaluga_kit.c
- bsp/esp32_s2_kaluga_kit/include/bsp/display.h
- bsp/esp32_s2_kaluga_kit/include/bsp/esp32_s2_kaluga_kit.h
- bsp/esp32_s3_eye/esp32_s3_eye.c
- bsp/esp32_s3_eye/include/bsp/display.h
- bsp/esp32_s3_eye/include/bsp/esp32_s3_eye.h
- bsp/esp32_s3_korvo_2/include/bsp/display.h
- bsp/esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
- bsp/esp32_s3_lcd_ev_board/include/bsp/display.h
- bsp/esp32_s3_lcd_ev_board/include/bsp/esp32_s3_lcd_ev_board.h
- bsp/esp32_s3_usb_otg/include/bsp/display.h
- bsp/esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h
- bsp/esp_bsp_generic/include/bsp/display.h
- bsp/esp_bsp_generic/include/bsp/esp_bsp_generic.h
- bsp/esp_wrover_kit/include/bsp/display.h
- bsp/esp_wrover_kit/include/bsp/esp_wrover_kit.h
* Added backlight functions to `bsp/display.h` so users can use them without including the main `bsp/esp-bsp.h`. This is important for future BSP version without LVGL
* Added capabilities of S3_eye board
* Add support for S3-EYE BOOT button
No need to release now
> fix bsp/display.h

- .github/ci/bsp_noglib.py
- .github/ci/update_readme_dependencies.py
- .github/workflows/upload_component.yml
- BSP_development_guide.md
- README.md
- bsp/esp32_s3_eye/esp32_s3_eye.c
- bsp/esp32_s3_eye/include/bsp/config.h
- bsp/esp32_s3_eye/include/bsp/esp32_s3_eye.h
With this change we can upload No Graphical Library (-noglib) versions of the BSPs. We must remove `esp_lvgl_port` from the list of dependencies and disable the relevant parts of code.
As an example only ESP32-S3-EYE is modified for this change
> feat: No graphical library in BSPs

- .pre-commit-config.yaml
This PR fixes errors with latest idf-component-manager
@kumekay The latest idf-component-manager v1.5.1 seems to incorrectly resolve conditional dependencies:
Here's the error: https://github.com/espressif/esp-bsp/actions/runs/7917759550/job/21614583839?pr=282#step:4:108
Here's the original idf_component.yml file: https://github.com/espressif/esp-bsp/blob/master/bsp/esp32_s3_lcd_ev_board/idf_component.yml
Could you please have a look too?
cc @espzav @pborcin
> fix(ci): Use fixed version of idf-component-manager

- components/lcd/esp_lcd_ili9881c/esp_lcd_ili9881c.c
- components/lcd/esp_lcd_ili9881c/idf_component.yml
Updated LCD ILI9881C initialization, set color mode. Add support for mirror x/y. Not supported swap XY by driver.
> LCD ILI9881C: Supported LCD mirror. Not supported swap XY.

- .github/ci/bsp_noglib.py
- .github/ci/update_readme_dependencies.py
- .github/workflows/upload_component_noglib.yml
- .gitignore
Extend noglib python script so it 
* accepts multiple BSPs
* renames the BSP automatically
* check the dependency table in readme automatically
If you want to add a new noglib BSP, only 2 changes are needed:
1. Add the BSP to this space separated list (eventually, this will include all BSPs) https://github.com/espressif/esp-bsp/blob/c1fd14695e295ce121a734345703dc0ec93e5d42/.github/workflows/upload_component_noglib.yml#L19
2. Add the noglib BSP to upload job https://github.com/espressif/esp-bsp/blob/c1fd14695e295ce121a734345703dc0ec93e5d42/.github/workflows/upload_component_noglib.yml#L25
> fix(ci): Extend noglib script to all BSPs

- bsp/esp-box-3/idf_component.yml
- bsp/esp-box-lite/idf_component.yml
- bsp/esp-box/idf_component.yml
- bsp/esp32_azure_iot_kit/idf_component.yml
- bsp/esp32_c3_lcdkit/idf_component.yml
- bsp/esp32_lyrat/idf_component.yml
- bsp/esp32_p4_function_ev_board/idf_component.yml
- bsp/esp32_s2_kaluga_kit/idf_component.yml
- bsp/esp32_s3_eye/idf_component.yml
- bsp/esp32_s3_korvo_1/idf_component.yml
- bsp/esp32_s3_korvo_2/idf_component.yml
- bsp/esp32_s3_lcd_ev_board/idf_component.yml
- bsp/esp32_s3_usb_otg/idf_component.yml
- bsp/esp_bsp_generic/idf_component.yml
- bsp/esp_wrover_kit/idf_component.yml
Updating BSPs descriptions to fix searching BSP packages on https://components.espressif.com/
Also adding a tag "bsp".
> Descriptions and tags updates (BSP-472)

- .github/ISSUE_TEMPLATE/01_Feature-Request.yml
- .github/ISSUE_TEMPLATE/02_Issue-Report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
Issue templates for esp-bsp repository
> Creating Issue templates (BSP-477)

- components/lcd_touch/esp_lcd_touch/idf_component.yml
- components/lcd_touch/esp_lcd_touch/include/esp_lcd_touch.h
- components/lcd_touch/esp_lcd_touch_gt911/README.md
- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/include/esp_lcd_touch_gt911.h
Closes BSP-468
1: Add dynamic setting for the I2C address.
> feat(GT911): added I2C addr set support. (BSP-496)

- bsp/m5stack_core_s3/idf_component.yml
- bsp/m5stack_core_s3/m5stack_core_s3.c
Fixed missing #if in LVGL display types for NOGLIB version of BSP
> fix(M5Stack CoreS3): Fixed display types for noglib version

- bsp/m5stack_core_s3/include/bsp/m5stack_core_s3.h
Fixes misspelling of "microSD" in docstring.
> fix(m5stack_cores3): correct typo in header (BSP-513)

- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
- Renamed function for rotation area in LVGL port (linking error with master LVGL)
> fix: Rename function for rotation area in LVGL port.

- components/esp_lvgl_port/README.md
LVGL9 seems to be stable now. Can we remove the warning?
> docs(esp_lvgl_port): remove LVGL9 unstable notice

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/CMakeLists.txt
- components/esp_lvgl_port/project_include.cmake
esp_lvgl_port component configuration is entirely dependent on LVGL's version. Moreover LVGL can be used as local or managed component. This PR aims to support all possible combinations
* Related to https://github.com/lvgl/lvgl/pull/6654
* esp_lvgl_port cannot be linked with LVGL's master branch, we must merge this first #362 
From esp_lvgl_port/CMakeLists.txt
``` cmake
```
> fix(esp_lvgl_port): Fix esp_lvgl_port with local LVGL component

- examples/display/main/lvgl_demo_ui.c
- examples/display_audio_photo/main/app_disp_fs.c
- examples/display_camera/main/display_camera.c
LVGL 9.2 makes `user_data` private. Access it with provided getter functions
> fix: Do not access LVGL 9.2 private members

- components/lcd/esp_lcd_ssd1681/CMakeLists.txt
- components/lcd/esp_lcd_ssd1681/idf_component.yml
- components/lcd_touch/esp_lcd_touch_cst816s/esp_lcd_touch_cst816s.c
- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_ft5x06/esp_lcd_touch_ft5x06.c
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt1151/esp_lcd_touch_gt1151.c
- components/lcd_touch/esp_lcd_touch_gt1151/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/esp_lcd_touch_tt21100.c
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
- test_app/CMakeLists.txt
All esp_lcd_touch drivers use I2C IO from esp_lcd, they do not directly depend on I2C driver.
Closes https://github.com/espressif/esp-bsp/issues/380
> fix(esp_lcd_touch): Remove i2c includes

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/include/esp_lvgl_port_compatibility.h
- Fixed rotation type compatibility with LVGL8 (issue with M5Stack Core S3 BSP)
> fix(LVGL port): Fixed rotation type compatibility with LVGL8.

- bsp/esp32_s3_korvo_1/CHANGELOG.md
- bsp/esp32_s3_korvo_1/esp32_s3_korvo_1_idf5.c
- bsp/esp32_s3_korvo_1/idf_component.yml
- bsp/esp32_s3_korvo_2/CHANGELOG.md
- bsp/esp32_s3_korvo_2/esp32_s3_korvo_2_idf5.c
- bsp/esp32_s3_korvo_2/idf_component.yml
- bsp/esp32_s3_lcd_ev_board/CHANGELOG.md
- bsp/esp32_s3_lcd_ev_board/idf_component.yml
- bsp/esp32_s3_lcd_ev_board/include/bsp/esp32_s3_lcd_ev_board.h
- bsp/esp32_s3_usb_otg/CHANGELOG.md
- bsp/esp32_s3_usb_otg/esp32_s3_usb_otg_idf5.c
- bsp/esp32_s3_usb_otg/idf_component.yml
* Explicit include `esp_adc/adc_cali_scheme.h` in BSP header to support IDF 5.0
`bsp` like `esp32_s3_usb_otg` `esp32_s3_lcd_ev_board` build under IDF 5.0 always failed with error:
```
.../managed_components/espressif__esp32_s3_usb_otg/esp32_s3_usb_otg_idf5.c:14:8: error: unknown type name 'adc_cali_handle_t'
14 | static adc_cali_handle_t bsp_adc_cali_handle; /* ADC1 calibration handle */
...
error: unknown type name 'adc_cali_curve_fitting_config_t'
```
The root cause is `esp_adc/adc_oneshot.h` in [IDF 5.0](https://github.com/espressif/esp-idf/blob/release/v5.0/components/esp_adc/include/esp_adc/adc_oneshot.h) not explicit include …
> fix(bsp): fix idf5.0 adc build with unknown type error

- .build-test-rules.yml
- components/ds18b20/examples/ds18b20-read/CMakeLists.txt
- components/ds18b20/examples/ds18b20-read/README.md
- components/ds18b20/examples/ds18b20-read/main/CMakeLists.txt
- components/ds18b20/examples/ds18b20-read/main/ds18b20-read.c
- components/ds18b20/examples/ds18b20-read/main/idf_component.yml
This PR adds a simple example of how to read the DS18B20. This example was used during a presentation to show how to use the components and BSP.
> Added example for the DS18B20

- bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
- bsp/esp32_p4_function_ev_board/idf_component.yml
- bsp/esp32_p4_function_ev_board/include/bsp/esp32_p4_function_ev_board.h
BSP uses old i2c interface. when another component such as esp-video uses new i2c interface. They will conflict.
> [fix] use new i2c interface for esp32_p4_function_ev_board. (BSP-545)

- bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
- bsp/esp32_p4_function_ev_board/idf_component.yml
SD card on P4 EV board is connected to slot 0. Previously the code used slot 1 and routed it through GPIO Matrix to slot 0 pins. This resulted in conflicts when trying to use slot 1 for connecting to ESP32-C6 over SDIO.
See https://github.com/espressif/esp-idf/issues/14699#issuecomment-2407264707 for background.
> fix(esp32_p4_function_ev_board): use slot 0 for SD card

- bsp/esp32_c3_lcdkit/esp32_c3_lcdkit.c
- bsp/esp32_s3_korvo_1/esp32_s3_korvo_1.c
- bsp/esp32_s3_korvo_1/idf_component.yml
- bsp/esp_bsp_devkit/idf_component.yml
- bsp/esp_bsp_devkit/src/esp_bsp_devkit.c
- bsp/esp_bsp_generic/idf_component.yml
- bsp/esp_bsp_generic/src/esp_bsp_generic.c
Recently a new version (v3.0.0) of led_strip was pushed. This changed the `led_strip_config_t` struct in the 
> led_strip/include/led_strip_types.h
file.
Please check the latest change of led_strip repository [here](https://github.com/espressif/idf-extra-components/commit/31585c8c97b5a403e1550270fb9fad58879cc2dd)
Closes https://github.com/espressif/esp-bsp/issues/420
> incorporating relevant changes from led_strip v3.0.0 (BSP-574)

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/include/esp_lvgl_port_disp.h
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
- Fixed SW rotation in LVGL9.2 (https://github.com/espressif/esp-bsp/issues/400)
- Fixed freeing right buffers when error
> fix(lvgl_port): Fixed SW rotation in LVGL9.2 and fixed free buffers.

- bsp/esp32_s3_lcd_ev_board/CHANGELOG.md
- bsp/esp32_s3_lcd_ev_board/idf_component.yml
- bsp/esp32_s3_lcd_ev_board/src/esp32_s3_lcd_ev_board.c
- Fixed LVGL8 compatibility in esp32_s3_lcd_ev_board
> fix(esp32_s3_lcd_ev_board): Fixed LVGL8 compatibility

- .build-test-rules.yml
- bsp/esp_bsp_devkit/idf_component.yml
- bsp/esp_bsp_devkit/include/bsp/esp_bsp_devkit.h
- bsp/esp_bsp_devkit/src/esp_bsp_devkit.c
- bsp/esp_bsp_generic/idf_component.yml
- bsp/esp_bsp_generic/include/bsp/esp_bsp_generic.h
- bsp/esp_bsp_generic/src/esp_bsp_generic.c
- Support I2C driver-NG for esp_bsp_generic and esp_bsp_devkit
> feat(esp_bsp_generic): Support I2C Driver-NG

- .build-test-rules.yml
This PR fixes the `components/lcd/esp_lcd_gc9503` if rule in the manifest file `build-test-rules.yml`.
Note: It only fixes parentheses in the rule, but I have a feeling (based on the reason in the rule), that `IDF_VERSION_MAJOR < 5` is redundant. If this is the case I will update the PR, otherwise I'll leave it as it is.
Before fix:
After fix:
> fix: Manifest .build-test-rules.yml rule (BSP-583)

- components/esp_lvgl_port/src/lvgl9/simd/lv_color_blend_to_argb8888_esp32s3.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_color_blend_to_rgb565_esp32s3.S
- components/esp_lvgl_port/test_apps/simd/README.md
- components/esp_lvgl_port/test_apps/simd/main/test_lv_fill_functionality.c
This PR adds rgb565 SIMD support  
- Follow-up for #357
> feature(lvgl_port): Add SIMD RGB565 support

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/examples/i2c_oled/README.md
- components/esp_lvgl_port/examples/i2c_oled/main/i2c_oled_example_main.c
- components/esp_lvgl_port/examples/i2c_oled/main/lvgl_demo_ui.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
- Fixed using monochromatic screens with LVGL port and LVGL9
- Support for LV_COLOR_FORMAT_I1 for monochromatic screen
> fix(LVGL port): Fixed monochromatic screen in LVGL9 + example

- components/lcd_touch/esp_lcd_touch_gt911/README.md
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
The **add-dependency** for **esp_lcd_touch_gt911** installs a version that is incompatible with the provided usage example.
**esp_lcd_touch_io_gt911_config_t** type is defined in version **1.1.1** [here](https://github.com/espressif/esp-bsp/commit/d118a01b29764b32c5ad2ec54fe0bf72f3769699#diff-9d9605942dc95af8aed100641fc40e7fe6ab8fdde90092e32197f8db3cd1bb2dR49) , so the **1.0.0** version is not compatible with the example.
> Wrong dependency version (BSP-590)

- bsp/esp_bsp_devkit/Kconfig
- bsp/esp_bsp_devkit/idf_component.yml
**Description:**
- add support for the esp32c5 chip.
- modify files in Kconfig to add support for esp32c5 related pins
- updat version number of esp_bsp_devkit
> feat: add_esp32c5_target (BSP-603)

- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_button.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_knob.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_touch.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_usbhid.c
`esp_lvgl_port` was using user data to store data. When I started wrapping the drivers in my project and using the user data, this broke `esp_lvgl_port`.
Since LVGL9, there's a "driver data" attribute, so I refactored the existing drivers to use the driver data functions instead, which frees up the user data, which can then be left to the user.
> Use driver_data instead of user_data (BSP-600)

- bsp/esp32_s3_usb_otg/Kconfig
- bsp/esp32_s3_usb_otg/esp32_s3_usb_otg.c
- bsp/esp32_s3_usb_otg/idf_component.yml
- bsp/esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h
> fix(esp32_s3_usb_otg): Renamed Kconfig SD mount option.

- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_cst816s/include/esp_lcd_touch_cst816s.h
ESP_LCD_TOUCH_IO_I2C_CST816S_CONFIG macro was causing warning under C++. I've added initialization to all fields.
> Fix(esp_lcd_touch_cst816s): Missing field initializers under C++ (BSP-609)

- components/lcd/esp_lcd_gc9a01/idf_component.yml
- components/lcd/esp_lcd_gc9a01/include/esp_lcd_gc9a01.h
GC9A01_PANEL_BUS_SPI_CONFIG and GC9A01_PANEL_IO_SPI_CONFIG macros were causing project to fail to compile in under C++23 (ESP-IDF 5.3.2). I've added initializers with default values for each member and fixed field order in BUS_SPI_CONFIG.
> Fix(esp_lcd_gc9a01): Missing field initializers and wrong order under C++ (BSP-610)

- .github/workflows/build-applications.yml
Separate modified files with semicolon: idf-build-apps expects semicolon separated list of modified files
- CI did not catch regression in #470 
- Related to #474
> CI: Separate modified files with semicolon

- components/.build-test-rules.yml
- components/esp_lvgl_port/examples/i2c_oled/main/CMakeLists.txt
Our CI was broken for some time and did not catch this issue.
Could close #481
Build i2c_example only for IDF >= 5.2
> fix(ci): Build i2c_example only for IDF >= 5.2

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c
Previously, we initialized LVGL in the new LVGL handling task. If lvgl_port_init() was called from high priority task, it could return with uninitialized LVGL.
Closes https://github.com/espressif/esp-bsp/issues/455
Closes https://github.com/espressif/esp-bsp/issues/475
> fix(esp_lvgl_port): Make sure LVGL is initialize at the end of lvgl_port_init() call

- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
- components/lcd_touch/esp_lcd_touch_cst816s/include/esp_lcd_touch_cst816s.h
Bug introduced in https://github.com/espressif/esp-bsp/pull/470
Closes https://github.com/espressif/esp-bsp/issues/485
> fix(cst816s): Provide 100kHz default value for SCL

- components/esp_lvgl_port/CMakeLists.txt
- components/esp_lvgl_port/include/esp_lvgl_port_lv_blend.h
- components/esp_lvgl_port/src/lvgl9/simd/lv_macro_memcpy.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_rgb565_blend_normal_to_rgb565_esp32.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_rgb565_blend_normal_to_rgb565_esp32s3.S
- components/esp_lvgl_port/test_apps/simd/README.md
- components/esp_lvgl_port/test_apps/simd/main/CMakeLists.txt
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/include/lv_draw_sw_blend.h
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/include/lv_string.h
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/include/lv_types.h
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/src/lv_draw_sw_blend_to_argb8888.c
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/src/lv_draw_sw_blend_to_rgb565.c
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/src/lv_string_builtin.c
- components/esp_lvgl_port/test_apps/simd/main/lv_fill_common.h
- components/esp_lvgl_port/test_apps/simd/main/lv_image_common.h
- components/esp_lvgl_port/test_apps/simd/main/test_lv_image_benchmark.c
- components/esp_lvgl_port/test_apps/simd/main/test_lv_image_functionality.c
This MR adds SIMD support for `LV_DRAW_SW_RGB565_BLEND_NORMAL_TO_RGB565` 
Which is basically a highly optimized memcpy for memory arrays with RGB565 color format
This addition relates RGB565 color format support from #438 : which is adding `memset` assembly support for RGB565 
- `esp32s3` SIMD assembly implementation of the `RGB565 to RGB565 memcpy`
- `esp32`  assembly implementation of the `RGB565 to RGB565 memcpy`
-  Added hard copy of `lv_sting_builtin.c` with LVGL's optimized memcpy and memset functions, for the benchmark tests to be credible, as some of the ANSI C LVGL SW rendering functions use `lv_memcpy` and `lv_memset`
- …
> feat(lvgl_port_simd): RBG565 image blend to RGB565

- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
1. Fix esp_lvgl_port buffer size in lvgl9, lv_color_t is 3 bytes in lvgl9, while lv_color_t is dynamic according to color format.
2. Add esp32_s3_eye spi dma support. Currently this is not support in esp-idf. As soon as esp-idf supports it, it will take affect.
> Fix/esp lvgl port (BSP-630)

- bsp/esp-box-3/include/bsp/esp-box-3.h
- bsp/esp-box-lite/include/bsp/esp-box-lite.h
- bsp/esp-box/include/bsp/esp-box.h
- bsp/esp32_c3_lcdkit/include/bsp/esp32_c3_lcdkit.h
- bsp/esp32_s3_eye/CMakeLists.txt
- bsp/esp32_s3_eye/idf_component.yml
- bsp/esp32_s3_eye/include/bsp/esp32_s3_eye.h
- bsp/esp32_s3_korvo_2/CHANGELOG.md
- bsp/esp32_s3_korvo_2/CMakeLists.txt
- bsp/esp32_s3_korvo_2/idf_component.yml
- bsp/esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
- bsp/esp32_s3_lcd_ev_board/include/bsp/esp32_s3_lcd_ev_board.h
- bsp/esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h
- bsp/m5stack_core_s3/include/bsp/m5stack_core_s3.h
- examples/display_camera/main/display_camera.c
* For BSP that exposed public function `i2c_master_bus_handle_t bsp_i2c_get_handle(void);` (korvo-2 and s3-eye), the `esp_driver_i2c` component must be listed in public dependencies
* On CoreS3 the camera is now enabled during `bsp_i2c_init()` call. Previously it was enabled during `bsp_display_new()`, but this caused problems if the users wanted to initialize the camera before LCD initialization
> Fix I2C NG includes

- components/esp_lvgl_port/CMakeLists.txt
- components/esp_lvgl_port/include/esp_lvgl_port_lv_blend.h
- components/esp_lvgl_port/src/lvgl9/simd/lv_color_blend_to_argb8888_esp32s3.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_color_blend_to_rgb565_esp32s3.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_color_blend_to_rgb888_esp32.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_color_blend_to_rgb888_esp32s3.S
- components/esp_lvgl_port/test_apps/simd/README.md
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/include/lv_draw_sw_blend_to_rgb888.h
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/src/lv_draw_sw_blend_to_rgb888.c
- components/esp_lvgl_port/test_apps/simd/main/lv_fill_common.h
- components/esp_lvgl_port/test_apps/simd/main/test_lv_fill_benchmark.c
- components/esp_lvgl_port/test_apps/simd/main/test_lv_fill_functionality.c
This MR adds SIMD support for LV_DRAW_SW_COLOR_BLEND_TO_RGB888
- `esp32s3`  SIMD assembly implementation of the `RGB888` simple fill
- `esp32` assembly implementation of the `RGB888` simple fill
- Functionality and benchmark tests
- Updated README with achieved benchmark results
> feature(lvgl_port): RGB888 SIMD fill

- components/ds18b20/CHANGELOG.md
- components/ds18b20/idf_component.yml
- components/ds18b20/include/ds18b20.h
- components/ds18b20/src/ds18b20.c
Add single ds18b20 device functionality with SKIP_ROM command, this way it safes the hassle of enumaration the bus when only 1 device is on the bus
> feat(ds18b20): Add single device mode (no enumeration 1-Wire bus) (BSP-637)

- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
Points should only get cleared on successfully read operations.
Before this patch, the touch driver reported no touch, when in fact there was touch but the GT911 was not ready to report data.
> Fix flickering when GT911 has no data to read (BSP-636)

- components/lcd_touch/esp_lcd_touch_ft5x06/esp_lcd_touch_ft5x06.c
- components/lcd_touch/esp_lcd_touch_ft5x06/idf_component.yml
- components/lcd_touch/esp_lcd_touch_gt911/esp_lcd_touch_gt911.c
- components/lcd_touch/esp_lcd_touch_gt911/idf_component.yml
- components/lcd_touch/esp_lcd_touch_stmpe610/esp_lcd_touch_stmpe610.c
- components/lcd_touch/esp_lcd_touch_stmpe610/idf_component.yml
- components/lcd_touch/esp_lcd_touch_tt21100/esp_lcd_touch_tt21100.c
- components/lcd_touch/esp_lcd_touch_tt21100/idf_component.yml
Taking the `esp_lcd_touch_ft5x06` component as an example, when `esp_lcd_touch_new_i2c_ft5x06()` fails, `out_touch` is still assigned a freed memory address. 
This PR fixes the issue by assigning the value before handling the `err:` label.
> fix(lcd_touch): avoid assigning a value to handle after creation failure

- bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
- bsp/esp32_p4_function_ev_board/idf_component.yml
- bsp/esp32_p4_function_ev_board/include/bsp/display.h
- bsp/esp32_p4_function_ev_board/include/bsp/esp32_p4_function_ev_board.h
- bsp/esp32_p4_function_ev_board/include/bsp/touch.h
- Add deinit/remove/delete functions for display
- Tested memory after deinit - some lazy init (static) still keep there
> bsp(esp32_p4_function_ev_board): Add deinit/remove/delete functions for display (BSP-598)

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/src/lvgl8/esp_lvgl_port_disp.c
- Fixed memory leak in LVGL8 in display removing
Closes #462
> fix(lvgl_port): Fixed memory leak in LVGL8 in display removing

- bsp/esp-box-3/idf_component.yml
- BSP for ESP-BOX-3 is not updated in component manager (missing button v4 fix)
> bsp(esp-box-3): Release latest fix.

- .github/workflows/doxygen.yml
- .github/workflows/squareline.yml
Previously used ubuntu-20.04 will be deprecated by 1.4.2025.
https://github.com/actions/runner-images/issues/11101
> ci: Update runners image to ubuntu-24.04

- bsp/m5stack_core_s3/idf_component.yml
- bsp/m5stack_core_s3/m5stack_core_s3.c
AW9523 P0 is set to push-pull mode only when speaker init.
Fix bus 5V without output because BUS_OUT_EN in Open-Drain mode.
> bsp(m5stack_coreS3): fix bus 5V without output because IO in Open-Dra… (BSP-653)

- bsp/esp32_p4_function_ev_board/CMakeLists.txt
- bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
- bsp/esp32_p4_function_ev_board/idf_component.yml
- bsp/esp32_p4_function_ev_board/include/bsp/esp32_p4_function_ev_board.h
- This is the proposal of the new API for SD card. There can be used MMC mode or SPI.
- Initialization is same and there is not breaking change.
- Only one breaking change: 
- - Removed `extern sdmmc_card_t *bsp_card;` --> New function `bsp_sdcard_get_handle()`
Closes #149
> feat(bsp): New SD card API (proposal) (BSP-189)

- bsp/esp32_s3_korvo_2/CHANGELOG.md
- bsp/esp32_s3_korvo_2/esp32_s3_korvo_2.c
- bsp/esp32_s3_korvo_2/idf_component.yml
I found that when using the esp32_s3_korvo_2 v3.0.1 BSP component, the I2C bus sometimes hangs (I2C master transmission gets stuck, triggering the task watchdog).
This issue can be reproduced using esp-bsp/examples/audio with IDF release/v5.4 or master.
```log
E (5794) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (5794) task_wdt:  - IDLE0 (CPU 0)
E (5794) task_wdt: Tasks currently running:
E (5794) task_wdt: CPU 0: audio_task
E (5794) task_wdt: CPU 1: IDLE1
E (5794) task_wdt: Print CPU 0 (current core) backtrace
Backtrace: 0x4201E1BA:0x3FC968B0 0x4201E5D0:0x3FC968D0 0x403777E1:0x3FC96900 0x4202DD7A:0x3FCEC6E0 0x4202DF88:0x3FCEC710 0x4202E06A:0x3FCEC750 0x4202EC3A:0x3FCEC780 0x4202ED12:0x3FCEC830 0x4200C0C9:0x3FCEC870 …
```
> fix(korvo_2): Fix I2C master transmission issue by adding glitch filtering (BSP-663)

- .github/workflows/build-run-applications.yml
- I found my issue in CI - new benchmarks was not saved into releases
Reverted (I am not sure with this change):
- Changed `on pull_request` to `on pull_request_target` (https://github.com/thollander/actions-comment-pull-request?tab=readme-ov-file#permissions)
> ci(runner): Fix benchmark results releases

- components/esp_lvgl_port/CMakeLists.txt
- components/esp_lvgl_port/include/esp_lvgl_port_lv_blend.h
- components/esp_lvgl_port/src/lvgl9/simd/lv_rgb888_blend_normal_to_rgb888_esp32.S
- components/esp_lvgl_port/src/lvgl9/simd/lv_rgb888_blend_normal_to_rgb888_esp32s3.S
- components/esp_lvgl_port/test_apps/simd/README.md
- components/esp_lvgl_port/test_apps/simd/main/lv_blend/src/lv_draw_sw_blend_to_rgb888.c
- components/esp_lvgl_port/test_apps/simd/main/lv_image_common.h
- components/esp_lvgl_port/test_apps/simd/main/test_lv_image_benchmark.c
- components/esp_lvgl_port/test_apps/simd/main/test_lv_image_functionality.c
This MR adds SIMD support for `LV_DRAW_SW_RGB565_BLEND_NORMAL_TO_RGB888`
Which is basically a highly optimized memcpy for memory arrays with RGB888 color format
- esp32s3 SIMD assembly implementation of the RGB888 to RGB888 memcpy
- esp32 assembly implementation of the RGB888 to RGB888 memcpy
- Functionality and benchmark tests
- Updated README with achieved benchmark results
> feat(lvgl_port_simd): RGB888 image blend to RGB888

- .github/workflows/pre-commit.yml
This MR updates actions in `pre-commit.yml` to unlock CI
pre-commit CI fail discovered in #559 
Failing CI Job [here](https://github.com/espressif/esp-bsp/actions/runs/14337518945/job/40188307139?pr=559#step:4:52)
The `pre-commit.yml` updated in accordance with `pre-commit.yml` from [esp-usb](https://github.com/espressif/esp-usb/blob/master/.github/workflows/pre-commit.yml)
> feat(ci): Update pre-commit actions due to deprecation

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/CMakeLists.txt
- components/esp_lvgl_port/Kconfig
- components/esp_lvgl_port/README.md
- components/esp_lvgl_port/idf_component.yml
- components/esp_lvgl_port/src/common/ppa/lcd_ppa.c
- components/esp_lvgl_port/src/common/ppa/lcd_ppa.h
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port_disp.c
- examples/display_lvgl_demos/main/dispaly_lvgl_demos_main.c
- Enabled PPA rotation in LVGL port (LVGL9 + P4)
Closes #540
> feat(lvgl_port): Used PPA for rotation on ESP32-P4

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/include/esp_lvgl_port.h
- components/esp_lvgl_port/src/lvgl8/esp_lvgl_port.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c
Closes https://github.com/espressif/esp-bsp/issues/567
Add option to pass memory capabilities to LVGL task. This gives users the flexibility to place LVGL's task stack to external RAM
> feat(esp_lvgl_port): Add LVGL task stack capabilities

- .github/workflows/build-run-applications.yml
- examples/display_lvgl_benchmark/pytest_display_lvgl_benchmark.py
- I decided to run build+run CI every day at midnight. We need to check if any other changes in components or IDF don't break our code.
- Fixed benchmarks - removed diff on master
> ci(build): Build and run all on master every midnight + fixed benchmarks on master

- components/bh1750/README.md
- components/fbm320/README.md
- components/hts221/README.md
- components/mag3110/README.md
- components/mpu6050/README.md
- test_apps/.build-test-rules.yml
- test_apps/components/CMakeLists.txt
1. Almost 0 usages in public projects
2. New driver in Sensor HUB
3. -> Deprecated
1. Few usages in public projects
2. New driver in Sensor HUB
3. -> Deprecated
1. Almost 0 usages in public projects
2. No other Espressif driver
3. -> As-is
1. Most used
2. New driver in Sensor HUB, but without ISR configuration
3. -> Passively maintained
1. Almost 0 usages in public projects
2. No other Espressif driver
3. -> As-is
> components: Add maintanance status badges

- .github/workflows/build-run-applications.yml
- conftest.py
- examples/display/pytest_display.py
- examples/display_lvgl_benchmark/main/main.c
- examples/display_lvgl_benchmark/pytest_display_lvgl_benchmark.py
- examples/display_lvgl_demos/pytest_display_lvgl_demos.py
- examples/display_sensors/pytest_display_display_sensors.py
- examples/generic_button_led/pytest_generic_button_led.py
- examples/generic_button_led/sdkconfig.bsp.esp_bsp_generic
- This is a PR for parallel process in CI Runner
> ci(runner): Process runner in parallel

- .github/workflows/upload_component_noglib.yml
- bsp/esp32_s3_korvo_2/API.md
- bsp/esp32_s3_korvo_2/esp32_s3_korvo_2.c
- bsp/esp32_s3_korvo_2/include/bsp/config.h
- bsp/esp32_s3_korvo_2/include/bsp/display.h
- bsp/esp32_s3_korvo_2/include/bsp/esp32_s3_korvo_2.h
- bsp/esp32_s3_lcd_ev_board/API.md
- bsp/esp32_s3_lcd_ev_board/README.md
- bsp/esp32_s3_lcd_ev_board/include/bsp/config.h
- bsp/esp32_s3_lcd_ev_board/include/bsp/display.h
- bsp/esp32_s3_lcd_ev_board/include/bsp/esp32_s3_lcd_ev_board.h
- bsp/esp32_s3_lcd_ev_board/src/esp32_s3_lcd_ev_board.c
Often used boards, Korvo-2 and LCD-EV board now have noglib versions.
\+ minor fixes
CI blocked by https://github.com/espressif/esp32-camera/pull/754
TODO
> feat: Add noglib options to Korvo 2 and LCD-EV board

- .github/ISSUE_TEMPLATE/01_Feature-Request.yml
- .github/ISSUE_TEMPLATE/02_Issue-Report.yml
This PR has 2 changes:
1. There was typo in issue forms for feature request. Correct label should be Feature Request with capital R
2. I changed single quotes to double ones in issue forms for bug, because documentation always uses double quotes
> fix(forms): fixing wrong label used and switching to double quotes (BSP-695)

- components/lcd_touch/esp_lcd_touch_cst816s/Kconfig
- components/lcd_touch/esp_lcd_touch_cst816s/README.md
- components/lcd_touch/esp_lcd_touch_cst816s/esp_lcd_touch_cst816s.c
- components/lcd_touch/esp_lcd_touch_cst816s/idf_component.yml
Some chips in the CST816 series may fail to read the ID during initialization. Therefore, Kconfig is added to allow the function of disabling ID reading.
> feat(cst816s): support disabling ID read via Kconfig

- components/esp_lvgl_port/include/esp_lvgl_port.h
- components/esp_lvgl_port/src/lvgl8/esp_lvgl_port.c
- components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c
By default, place LVGL task stack in internal RAM to avoid issues with cache if SPIRAM is used.
If placed in external RAM, following error can raise:
```
assert failed: spi_flash_disable_interrupts_caches_and_other_cpu cache_utils.c:127 (esp_task_stack_is_sane_cache_disabled())
```
> fix(esp_lvgl_port): Place LVGL task stack to internal RAM

- bsp/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c
- components/lcd/esp_lcd_ili9881c/idf_component.yml
- components/lcd/esp_lcd_ili9881c/include/esp_lcd_ili9881c.h
- components/lcd/esp_lcd_lt8912b/idf_component.yml
- components/lcd/esp_lcd_lt8912b/include/esp_lcd_lt8912b.h
- components/lcd/esp_lcd_st7796/idf_component.yml
- components/lcd/esp_lcd_st7796/include/esp_lcd_st7796.h
The dphy pll reference clock got changed in esp32p4 version 3.0. The real default clock source are different between major versions.
But using `0` as default can work for all P4 version, the driver will select a default clock source automatically.
> refactor(mipi_lcd): set phy_clk_src to 0 as default clock source

- components/esp_lvgl_port/CHANGELOG.md
- components/esp_lvgl_port/idf_component.yml
- Changed minimum IDF version of LVGL port to IDF5.1
- Closes #643
> fix(esp_lvgl_port): Change minimum IDF version
